### ISSUE TITLE
error information

### ISSUE THREAD

**Issue by cploveflower** [yuanming-hu/fc4#35]
this is the error information of train：
E:\cp\light\fc4-master>python3 fc4.py train model
2019-03-19 16:34:36.920164: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
FOLD 0
['g0', 'g1']
['g2']
Traceback (most recent call last):
  File "fc4.py", line 243, in <module>
    globals()[mode](*sys.argv[2:])
  File "fc4.py", line 175, in train
    fcn = FCN(sess=sess, name=name, kwargs=kwargs)
  File "E:\cp\light\fc4-master\fcn.py", line 53, in __init__
    self.build()
  File "E:\cp\light\fc4-master\fcn.py", line 173, in build
    fc2 = self.build_branches(self.images, self.dropout)
  File "E:\cp\light\fc4-master\fcn.py", line 88, in build_branches
    alex_outputs = create_convnet(alex_images)
  File "E:\cp\light\fc4-master\squeeze_net.py", line 233, in create_convnet
    sn = SqueezeNet(imgs)
  File "E:\cp\light\fc4-master\squeeze_net.py", line 16, in __init__
    self.build_model()
  File "E:\cp\light\fc4-master\squeeze_net.py", line 22, in build_model
    self.model = pkl.load(open(MODEL_PATH),'r')
TypeError: Function takes at most 1 positional arguments (2 given)

**Comment by cploveflower** [comment]
I have solved it,Thank you!

**Comment by hihanchang** [comment]
Hi, can you tell me how to solve this problem?
