### ISSUE TITLE
TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed.

### ISSUE THREAD

**Issue by yt605155624** [yuanming-hu/fc4#8]
Hello ,I am using tensorflow-gpu 1.2.0 to run your training code and meet this problem
Traceback (most recent call last):
  File "fc4.py", line 240, in <module>
    globals()[mode](*sys.argv[2:])
  File "fc4.py", line 172, in train
    fcn = FCN(sess=sess, name=name, kwargs=kwargs)
  File "/media/yt/fc4/fcn.py", line 54, in __init__
    self.build()
  File "/media/yt/fc4/fcn.py", line 174, in build
    fc2 = self.build_branches(self.images, self.dropout)
  File "/media/yt/fc4/fcn.py", line 107, in build_branches
    fc1 = slim.dropout(fc1, dropout)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1216, in dropout
    _scope=sc)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/core.py", line 247, in __init__
    self.rate = min(1., max(0., rate))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 578, in __nonzero__
    raise TypeError("Using a `tf.Tensor` as a Python `bool` is not allowed. "
TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use TensorFlow ops such as tf.cond to execute subgraphs conditioned on the value of a tensor.

It said that  I should  **Use `if t is not None:` instead of `if t:** but I can't find a "if t " in your code,Could you please help me to fix this problem?

**Comment by yuanming-hu** [comment]
Sure. I will take a look later tonight. Thanks!

**Comment by yuanming-hu** [comment]
Oh, then tf-gpu 1.7.0 should be fine. Could you just try tf-gpu 1.7.0?

Thx
